### ISSUE TITLE
Custom packages don't work for latest versions 

### ISSUE THREAD

**Issue by kaarthik108** [snowflakedb/snowpark-python#1067]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

  ` Python 3.10.0 (default, Aug 15 2023, 22:34:54) [Clang 14.0.3 (clang-1403.0.22.14.1)]`

2. What operating system and processor architecture are you using?

   `macOS-13.5.2-arm64-arm-64bit`

3. What are the component versions in the environment (`pip freeze`)?

4. What did you do?
5. 
I am trying to add the latest version of langchain as a zip has the anaconda version is way too old

`session.custom_package_usage_config = {"enabled": True}`
`session.add_packages(["langchain==0.0.305"])`

which says 

> Traceback (most recent call last):
  Worksheet, line 10, in main
  File "snowflake/snowpark/session.py", line 829, in add_packages
    self._resolve_packages(
  File "snowflake/snowpark/session.py", line 980, in _resolve_packages
    raise RuntimeError(
RuntimeError: Cannot add package langchain(version 0.0.304) because it is not available in Snowflake and it cannot be installed via pip as you are executing this code inside a stored procedure. You can find the directory of these packages and add it via Session.add_import. See details at https://docs.snowflake.com/en/developer-guide/snowpark/python/creating-udfs.html#using-third-party-packages-from-anaconda-in-a-udf.

6. What did you expect to see?

  Instead of zipping the file it errors out. 

7. Can you set logging to DEBUG and collect the logs?

**Comment by sfc-gh-stan** [comment]
Hi @kaarthik108 , looks like you are executing this in a Python worksheet, which means the code runs in a Python stored procedure. This feature is not supported inside stored procedures.
