### ISSUE TITLE
SNOW-1427770: [Local testing] Table merge fails when update clause exists but no update takes place

### ISSUE THREAD

**Issue by mraraujo** [snowflakedb/snowpark-python#1590]
1. What version of Python are you using?

3.11.6

2. What operating system and processor architecture are you using?

Linux-6.5.0-28-generic-x86_64-with-glibc2.38

3. What are the component versions in the environment (`pip freeze`)?

Snowpark version 1.16.0

4. What did you do?
```
from snowflake.snowpark import Session
from snowflake.snowpark.functions import when_matched, when_not_matched

session = Session.builder.config('local_testing', True).create()

target = session.create_dataframe([[1, "a"]], schema=['id', 'name'])
target.write.save_as_table('target', mode='overwrite')
target = session.table('target')

source = session.create_dataframe([[2, "b"]], schema=['id', 'name'])

target.merge(source, target['id'] == source['id'], [when_matched().update({'name': source['name']}), when_not_matched().insert({'id': source['id'], 'name': source['name']})])
```

5. What did you expect to see?

The target table should have one additional row with id 2.
Instead, we get an exception:

```
Traceback (most recent call last):
  File "/home/maraujo/Desktop/test.py", line 12, in <module>
    target.merge(source, target['id'] == source['id'], [when_matched().update({'name': source['name']}), when_not_matched().insert({'id': source['id'], 'name': source['name']})])
  File "/home/maraujo/venvs/semantec-backend/lib/python3.11/site-packages/snowflake/snowpark/table.py", line 677, in merge
    _get_merge_result(
  File "/home/maraujo/venvs/semantec-backend/lib/python3.11/site-packages/snowflake/snowpark/table.py", line 253, in _get_merge_result
    rows_updated = int(rows[0][idx])
                       ~~~~~~~^^^^^
  File "/home/maraujo/venvs/semantec-backend/lib/python3.11/site-packages/snowflake/snowpark/row.py", line 142, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
```

Note that nothing fails if the source dataframe also provides an update. E.g., changing the source to this:
```
source = session.create_dataframe([[1, "c"], [2, "b"]], schema=['id', 'name'])
```

succeeds.

6. Can you set logging to DEBUG and collect the logs?
```
2024-05-15 18:11:59,423 - MainThread session.py:500 - __init__() - INFO - Snowpark Session information: 
"version" : 1.16.0,
"python.version" : 3.11.6,
"python.connector.version" : 3.10.0,
"python.connector.session.id" : 1,
"os.name" : Linux

Traceback (most recent call last):
  File "/home/maraujo/Desktop/test.py", line 22, in <module>
    target.merge(source, target['id'] == source['id'], [when_matched().update({'name': source['name']}), when_not_matched().insert({'id': source['id'], 'name': source['name']})])
  File "/home/maraujo/venvs/semantec-backend/lib/python3.11/site-packages/snowflake/snowpark/table.py", line 677, in merge
    _get_merge_result(
  File "/home/maraujo/venvs/semantec-backend/lib/python3.11/site-packages/snowflake/snowpark/table.py", line 253, in _get_merge_result
    rows_updated = int(rows[0][idx])
                       ~~~~~~~^^^^^
  File "/home/maraujo/venvs/semantec-backend/lib/python3.11/site-packages/snowflake/snowpark/row.py", line 142, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range
2024-05-15 18:11:59,485 - MainThread session.py:527 - close() - DEBUG - No-op because session 1 had been previously closed.
2024-05-15 18:11:59,485 - MainThread session.py:539 - close() - INFO - Closed session: 1
2024-05-15 18:12:03,186 - MainThread _telemetry.py:113 - _upload_payload() - DEBUG - telemetry server request success: 200
2024-05-15 18:12:03,186 - MainThread _telemetry.py:129 - _upload_payload() - DEBUG - Telemetry request success=True
```

**Comment by sfc-gh-sghosh** [comment]
Hello @mraraujo ,

Thanks for raising the issue; we are looking into it and will update you.

Regards,
Sujan

**Comment by sfc-gh-sghosh** [comment]
Hello @mraraujo ,

We are able to reproduce the issue, will work on eliminating it, and will update you.

Regards,
Sujan

**Comment by mraraujo** [comment]
Thanks for the update.

**Comment by sfc-gh-aling** [comment]
this is a bug in local testing that the occurrence of clause should be used to detect whether there is update happening not on the data being updated.

I have a PR out for fix the issue: https://github.com/snowflakedb/snowpark-python/pull/1719

**Comment by sfc-gh-aling** [comment]
we have merged the PR, it will be carried in our next release which is expected to happen next week.
to try out the fix now, you can install from the git main branch: pip install git+https://github.com/snowflakedb/snowpark-python.git
