### ISSUE TITLE
SNOW-654151: DataFrame.write.save_as_table() raises exception in snowpark-python 0.8.0

### ISSUE THREAD

**Issue by WillGAB** [snowflakedb/snowpark-python#460]
1. What version of Python are you using?
I'm running Snowpark in a Snowflake stored procedure with:
```sql
language python
runtime_version = 3.8
```

2. What operating system and processor architecture are you using?
The bug occurs in a Snowflake stored procedure which appears to be running  `Linux-5.4.181-99.354.amzn2.aarch64-aarch64-with-glibc2.34` 

4. What are the component versions in the environment (`pip freeze`)?
I'm using the native Snowpark python environment (as specified above). The only package included is:
`packages = ('snowflake-snowpark-python==0.8.0')`

5. What did you do?
Attempted to write a dataframe to a snowflake table using:
`DataFrame.write.save_as_table(destination_table_name, mode="append")`

6. What did you expect to see?
I expected the dataframe to be written to the specified table. Instead, the write consistently raises the exception `TypeError: argument of type 'NoneType' is not iterable` (stack trace below). 

Extra details:
- Works as expected with `snowflake-snowpark-python==0.7.0`
- Appears to work when writing a dataframe with a very small number of rows (on the order of 10), but fails even for around 100 rows. Potentially points to a bug related to batch inserts?

Stack trace:
```
Python Interpreter Error:
Traceback (most recent call last):
  File "_udf_code.py", line 66, in run
  File "_udf_code.py", line 111, in write_alerts_to_database
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/telemetry.py", line 165, in wrap
    result = func(*args, **kwargs)
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/dataframe_writer.py", line 142, in save_as_table
    session._conn.execute(snowflake_plan, _statement_params=statement_params)
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/server_connection.py", line 369, in execute
    result_set, result_meta = self.get_result_set(
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/analyzer/snowflake_plan.py", line 81, in wrap
    return func(*args, **kwargs)
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/server_connection.py", line 407, in get_result_set
    self.run_batch_insert(query.sql, query.rows, **kwargs)
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/server_connection.py", line 104, in wrap
    raise ex
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/server_connection.py", line 98, in wrap
    return func(*args, **kwargs)
  File "/usr/lib/python_udf/1adf2bad1b775134282f52c6525f68044babf4feecd5a313ae7083de4f58eaa3/lib/python3.8/site-packages/snowflake/snowpark/_internal/server_connection.py", line 458, in run_batch_insert
    and "QUERY_TAG" in kwargs["_statement_params"]
TypeError: argument of type 'NoneType' is not iterable
 in function TEST_PROC with handler run
```

7. Can you set logging to DEBUG and collect the logs?
Happy to do so if possible, but would need some help to understand I can get the stored procedure to output the logs.

**Comment by sfc-gh-jdu** [comment]
It has been fixed in https://github.com/snowflakedb/snowpark-python/commit/34a28a5f541bb9635d769381d477c2f2dea56873, which already went out with 0.9.0 release. https://pypi.org/project/snowflake-snowpark-python/0.9.0/
