### ISSUE TITLE
SNOW-847321: Missing optional dependency: pandas despite no pandas dataframe being used

### ISSUE THREAD

**Issue by bjorhn** [snowflakedb/snowpark-python#910]
A bug introduced in 1.5.0 is causing some dependency check logic to mistake lists (and likely other data structures) for pandas dataframes. See below for more info, including an MRE.

The issue can likely be worked around by installing pandas, but my understanding is that this shouldn't be necessary.

1. What version of Python are you using?

```
Python 3.8.17 (default, Jun 13 2023, 16:09:51) 
[GCC 10.2.1 20210110]
```

2. What operating system and processor architecture are you using?

`
Linux-5.15.0-1040-azure-x86_64-with-glibc2.2.5
`

3. What are the component versions in the environment (`pip freeze`)?

```
adlfs==2023.4.0
aiohttp==3.8.4
aiosignal==1.3.1
aiosqlite==0.19.0
alembic==1.11.1
anyio==3.7.0
apprise==1.4.0
asgi-lifespan==2.1.0
asn1crypto==1.5.1
astroid==2.15.5
asttokens==2.2.1
async-timeout==4.0.2
asyncpg==0.27.0
attrs==23.1.0
autopep8==2.0.2
azure-common==1.1.28
azure-core==1.27.0
azure-datalake-store==0.0.53
azure-identity==1.13.0
azure-keyvault-secrets==4.7.0
azure-mgmt-containerinstance==10.1.0
azure-mgmt-core==1.4.0
azure-mgmt-resource==23.0.1
azure-storage-blob==12.16.0
azure-storage-file-datalake==12.11.0
backcall==0.2.0
backports.zoneinfo==0.2.1
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
cfgv==3.3.1
charset-normalizer==3.1.0
click==8.1.3
cloudpickle==2.0.0
colorama==0.4.6
coolname==2.2.0
croniter==1.4.1
cryptography==40.0.2
dateparser==1.1.8
decorator==5.1.1
dill==0.3.6
distlib==0.3.6
docker==6.1.3
exceptiongroup==1.1.1
executing==1.2.0
fancycompleter==0.9.1
fastapi==0.98.0
filelock==3.12.2
frozenlist==1.3.3
fsspec==2023.6.0
google-auth==2.20.0
greenlet==2.0.2
griffe==0.29.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.17.2
httpx==0.24.1
hyperframe==6.0.1
identify==2.5.24
idna==3.4
importlib-metadata==6.7.0
importlib-resources==5.12.0
iniconfig==2.0.0
ipython==8.12.2
isodate==0.6.1
isort==5.12.0
jedi==0.18.2
Jinja2==3.1.2
jsonpatch==1.33
jsonpath-ng==1.5.3
jsonpointer==2.4
jsonschema==4.17.3
kubernetes==26.1.0
lazy-object-proxy==1.9.0
Mako==1.2.4
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
mccabe==0.7.0
mdurl==0.1.2
msal==1.22.0
msal-extensions==1.0.0
multidict==6.0.4
nodeenv==1.8.0
oauthlib==3.2.2
orjson==3.9.1
oscrypto==1.3.0
packaging==23.1
parso==0.8.3
pathspec==0.11.1
pdbpp==0.10.3
pendulum==2.1.2
pexpect==4.8.0
pickleshare==0.7.5
pkgutil_resolve_name==1.3.10
platformdirs==3.7.0
pluggy==1.2.0
ply==3.11
portalocker==2.7.0
pre-commit==3.3.2
prefect==2.10.16
prefect-azure==0.2.10
prefect-snowflake==0.26.1
prompt-toolkit==3.0.38
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.10.0
pycparser==2.21
pycryptodomex==3.18.0
pydantic==1.10.9
pydocstyle==6.3.0
pyflakes==3.0.1
Pygments==2.15.1
PyJWT==2.7.0
pylama==8.4.1
pylint==2.17.4
pyOpenSSL==23.2.0
pyrepl==0.9.0
pyrsistent==0.19.3
pytest==7.3.1
python-dateutil==2.8.2
python-slugify==8.0.1
pytz==2023.3
pytzdata==2020.1
PyYAML==6.0
readchar==4.0.5
regex==2023.6.3
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.4.2
rsa==4.9
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
snowflake-connector-python==3.0.4
snowflake-snowpark-python==1.5.1
sortedcontainers==2.4.0
SQLAlchemy==2.0.16
stack-data==0.6.2
starlette==0.27.0
text-unidecode==1.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.8
traitlets==5.9.0
typer==0.9.0
typing_extensions==4.6.3
tzlocal==5.0.1
urllib3==1.26.16
uvicorn==0.22.0
virtualenv==20.23.1
wcwidth==0.2.6
websocket-client==1.6.0
websockets==11.0.3
wmctrl==0.4
wrapt==1.15.0
yarl==1.9.2
zipp==3.15.0
```

4. What did you do?

I upgraded to snowpark-python 1.5.1 (from 1.4.0). I believe the cause of the issue is the "missing dependency check improvement" introduced in #837, which was included in the 1.5.0 release.

I've put together an MRE:
```python
import os
from snowflake.snowpark.session import Session

def do_things():
    connection_parameters = {
        "account": os.environ['SNOWFLAKE_ACCOUNT'],
        "user": os.environ['SNOWFLAKE_USER'],
        "warehouse": os.environ['SNOWFLAKE_WAREHOUSE'],
        "role": os.environ['SNOWFLAKE_ROLE'],
        "database": os.environ['SNOWFLAKE_DATABASE'],
        "password": "***redacted***"
    }

    list_of_strings = ["this", "is", "a", "list"]

    session = Session.builder.configs(connection_parameters).create()
    session.create_dataframe(list_of_strings) # This throws an exception

if __name__ == "__main__":
    do_things()
```

5. What did you expect to see?

I expect the MRE to pass without an error. Instead, create_dataframe throws an exception saying the pandas dependency is missing. It appears that the list of strings passed to the function is mistaken for a pandas dataframe.

```bash
Traceback (most recent call last):
  File "snowpark_mre.py", line 20, in <module>
    do_things()
  File "snowpark_mre.py", line 17, in do_things
    session.create_dataframe(list_of_strings)
  File "/home/vscode/.cache/pypoetry/virtualenvs/full/lib/python3.8/site-packages/snowflake/snowpark/session.py", line 1473, in create_dataframe
    if not isinstance(data, (list, tuple, pandas.DataFrame)):
  File "/home/vscode/.cache/pypoetry/virtualenvs/full/lib/python3.8/site-packages/snowflake/connector/options.py", line 44, in __getattr__
    raise errors.MissingDependencyError(self._dep_name)
snowflake.connector.errors.MissingDependencyError: Missing optional dependency: pandas
```

**Comment by sfc-gh-sfan** [comment]
@bjorhn : Thanks for reporting. This looks like a bug to me introduced by https://github.com/snowflakedb/snowpark-python/commit/549a17c1e0a5134602bbb9150349957f03609b0e (thanks @sfc-gh-stan )

`if not installed_pandas and isinstance(data, pandas.DataFrame):`

If I'm reading it correctly, if the user does not install `pandas`, then we will try to load `pandas.DataFrame` for `isinstance` check and trigger this error. We'll fix this in the next release.

**Comment by sfc-gh-azhan** [comment]
The idea was trying to provider better message if pandas is not imported but the bug happened and delivered this `snowflake.connector.errors.MissingDependencyError: Missing optional dependency: pandas` :slightly_smiling_face: not too bad, but the code needs to fix.
